require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NetworkLinksController do

  # This should return the minimal set of attributes required to create a valid
  # NetworkLink. As you add validations to NetworkLink, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "start_lat" => "1.5" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NetworkLinksController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all network_links as @network_links" do
      network_link = NetworkLink.create! valid_attributes
      get :index, {}, valid_session
      assigns(:network_links).should eq([network_link])
    end
  end

  describe "GET show" do
    it "assigns the requested network_link as @network_link" do
      network_link = NetworkLink.create! valid_attributes
      get :show, {:id => network_link.to_param}, valid_session
      assigns(:network_link).should eq(network_link)
    end
  end

  describe "GET new" do
    it "assigns a new network_link as @network_link" do
      get :new, {}, valid_session
      assigns(:network_link).should be_a_new(NetworkLink)
    end
  end

  describe "GET edit" do
    it "assigns the requested network_link as @network_link" do
      network_link = NetworkLink.create! valid_attributes
      get :edit, {:id => network_link.to_param}, valid_session
      assigns(:network_link).should eq(network_link)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new NetworkLink" do
        expect {
          post :create, {:network_link => valid_attributes}, valid_session
        }.to change(NetworkLink, :count).by(1)
      end

      it "assigns a newly created network_link as @network_link" do
        post :create, {:network_link => valid_attributes}, valid_session
        assigns(:network_link).should be_a(NetworkLink)
        assigns(:network_link).should be_persisted
      end

      it "redirects to the created network_link" do
        post :create, {:network_link => valid_attributes}, valid_session
        response.should redirect_to(NetworkLink.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved network_link as @network_link" do
        # Trigger the behavior that occurs when invalid params are submitted
        NetworkLink.any_instance.stub(:save).and_return(false)
        post :create, {:network_link => { "start_lat" => "invalid value" }}, valid_session
        assigns(:network_link).should be_a_new(NetworkLink)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        NetworkLink.any_instance.stub(:save).and_return(false)
        post :create, {:network_link => { "start_lat" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested network_link" do
        network_link = NetworkLink.create! valid_attributes
        # Assuming there are no other network_links in the database, this
        # specifies that the NetworkLink created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        NetworkLink.any_instance.should_receive(:update).with({ "start_lat" => "1.5" })
        put :update, {:id => network_link.to_param, :network_link => { "start_lat" => "1.5" }}, valid_session
      end

      it "assigns the requested network_link as @network_link" do
        network_link = NetworkLink.create! valid_attributes
        put :update, {:id => network_link.to_param, :network_link => valid_attributes}, valid_session
        assigns(:network_link).should eq(network_link)
      end

      it "redirects to the network_link" do
        network_link = NetworkLink.create! valid_attributes
        put :update, {:id => network_link.to_param, :network_link => valid_attributes}, valid_session
        response.should redirect_to(network_link)
      end
    end

    describe "with invalid params" do
      it "assigns the network_link as @network_link" do
        network_link = NetworkLink.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NetworkLink.any_instance.stub(:save).and_return(false)
        put :update, {:id => network_link.to_param, :network_link => { "start_lat" => "invalid value" }}, valid_session
        assigns(:network_link).should eq(network_link)
      end

      it "re-renders the 'edit' template" do
        network_link = NetworkLink.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NetworkLink.any_instance.stub(:save).and_return(false)
        put :update, {:id => network_link.to_param, :network_link => { "start_lat" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested network_link" do
      network_link = NetworkLink.create! valid_attributes
      expect {
        delete :destroy, {:id => network_link.to_param}, valid_session
      }.to change(NetworkLink, :count).by(-1)
    end

    it "redirects to the network_links list" do
      network_link = NetworkLink.create! valid_attributes
      delete :destroy, {:id => network_link.to_param}, valid_session
      response.should redirect_to(network_links_url)
    end
  end

end
